# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "4761554e62d20462c9ec46fdb72666cd734b4973"

[[deps.MetricaBase]]
path = "."
uuid = "9f6ff2ae-77f1-47e1-8d02-c1542b05cf6b"
version = "0.1.0"
